---
kubernetes_cni_manifest_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
kubernetes_cri_socket: "unix:///run/containerd/containerd.sock"
kubernetes_kubeadm_init_extra_args: []
kubernetes_pod_network_cidr: "10.244.0.0/16"
