stages:
  - secret-detection
  - lint
  - post-sast
  - fetch
  - test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

sast:
  stage: test

secret_detection:
  stage: secret-detection
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

trufflehog:
  stage: secret-detection
  image:
    name: trufflesecurity/trufflehog:latest
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - trufflehog git file://. --fail --json > trufflehog-report.json
  artifacts:
    when: always
    paths:
      - trufflehog-report.json
    expire_in: 1 week

.sast-analyzer:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

ansible_lint:
  stage: lint
  tags:
    - ansible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - ansible-lint

parse-sast-results:
  stage: post-sast
  image: alpine:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache jq
  script:
    - echo "=== SECRET DETECTION RESULTS ==="
    - |
      if [ -f "gl-secret-detection-report.json" ]; then
        jq -r '.vulnerabilities[] |
          "Severity: [\(.severity)] | Category: \(.category) \n" +
          "Description: \(.message) \n" +
          "Location: \(.location.file):\(.location.start_line)\n" +
          "-----------------------------------"' gl-secret-detection-report.json
      else
        echo "gl-secret-detection-report.json not found."
      fi
    - echo "=== SAST RESULTS ==="
    - |
      if [ -f "gl-sast-report.json" ]; then
        jq -r '.vulnerabilities[] |
          "Severity: [\(.severity)] | Category: \(.category) \n" +
          "Description: \(.message) \n" +
          "Location: \(.location.file):\(.location.start_line)\n" +
          "-----------------------------------"' gl-sast-report.json
      else
        echo "gl-sast-report.json not found."
      fi

.vagrant_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - changes:
        - playbooks/roles/workstation/**
        - playbooks/roles/base/**

run_vagrant_arch:
  extends: .vagrant_rules
  stage: test
  resource_group: vagrant
  interruptible: true
  variables:
    VAGRANT_DEFAULT_PROVIDER: libvirt
    ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass
  tags:
    - ansible
  before_script:
    - echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/cf_homelab/secrets.git
    - ./scripts/link-private-files.sh --secrets-dir secrets
  script:
    - virsh destroy ansible_nodes_arch-test || true
    - virsh undefine ansible_nodes_arch-test --remove-all-storage || true
    - |
      for pool in $(virsh pool-list --all --name | grep ansible_nodes); do
        virsh pool-destroy "$pool" || true
        virsh pool-undefine "$pool" || true
      done
    - vagrant up arch-test
  after_script:
    - rm -f .vault_pass
    - vagrant destroy -f arch-test

run_vagrant_fedora:
  extends: .vagrant_rules
  stage: test
  resource_group: vagrant
  interruptible: true
  variables:
    VAGRANT_DEFAULT_PROVIDER: libvirt
    ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass
  tags:
    - ansible
  before_script:
    - echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/cf_homelab/secrets.git
    - ./scripts/link-private-files.sh --secrets-dir secrets
  script:
    - virsh destroy ansible_nodes_fedora-test || true
    - virsh undefine ansible_nodes_fedora-test --remove-all-storage || true
    - |
      for pool in $(virsh pool-list --all --name | grep ansible_nodes); do
        virsh pool-destroy "$pool" || true
        virsh pool-undefine "$pool" || true
      done
    - vagrant up fedora-test
  after_script:
    - rm -f .vault_pass
    - vagrant destroy -f fedora-test

run_vagrant_ubuntu:
  extends: .vagrant_rules
  stage: test
  resource_group: vagrant
  interruptible: true
  variables:
    VAGRANT_DEFAULT_PROVIDER: libvirt
    ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass
  tags:
    - ansible
  before_script:
    - echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/cf_homelab/secrets.git
    - ./scripts/link-private-files.sh --secrets-dir secrets
  script:
    - virsh destroy ansible_nodes_ubuntu-test || true
    - virsh undefine ansible_nodes_ubuntu-test --remove-all-storage || true
    - |
      for pool in $(virsh pool-list --all --name | grep ansible_nodes); do
        virsh pool-destroy "$pool" || true
        virsh pool-undefine "$pool" || true
      done
    - vagrant up ubuntu-test
  after_script:
    - rm -f .vault_pass
    - vagrant destroy -f ubuntu-test
