---
- name: update_tmux_plugin_perms
  ansible.builtin.file:
    path: /home/christoffer/.tmux/plugins
    owner: christoffer
    group: christoffer
    recurse: true

- name: update_zsh_plugin_perms
  ansible.builtin.file:
    path: /home/christoffer/.oh-my-zsh/custom/plugins
    owner: christoffer
    group: christoffer
    recurse: true

- name: ZSH | Cleanup oh-my-zsh install script
  ansible.builtin.file:
    path: /tmp/oh-my-zsh_install.sh
    state: absent
