export EDITOR=nvim

if ! command -v "$starship" > /dev/null;
then
  eval "$(starship init bash)"
fi

for file in $HOME/.config/bash/*.sh; do
  source "$file"
done

# Fuzzy completion
source <(fzf --bash)

# history
HISTFILE=~/.bash_history
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%Y-%m-%d %T "
HISTSIZE=10000
HISTFILESIZE=10000
shopt -s histappend

export PATH="$HOME/bin:$PATH"
