---
- name: system setup | microcode | install package for amd
  tags: amd,cpu,microcode,system setup
  ansible.builtin.package:
    name: amd64-microcode
  when:
    - microcode_amd_install is defined
    - microcode_amd_install
    - ansible_facts['distribution'] in ['Ubuntu', 'Debian', 'LMDE'] # Fedora already includes in linux-firmware package

- name: system setup | microcode | install package for intel
  tags: cpu,intel,microcode,system setup
  ansible.builtin.package:
    name: intel-microcode
  when:
    - microcode_intel_install is defined
    - microcode_intel_install
    - ansible_facts['distribution'] in ['Ubuntu', 'Debian', 'LMDE'] # Fedora already includes in linux-firmware package
