---
- name: end of run cleanup
  hosts: all
  become: true
  tasks:
    - name: cleanup package cache (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoclean: true
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    - name: autoremove orphan packages (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']
