---
- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: "files/users/christoffer/bash/bashrc"
    dest: "/home/christoffer/.bashrc"
    owner: christoffer
    group: christoffer
    mode: "0644"

- name: "Bash | Copy custom bash config"
  ansible.builtin.copy:
    src: "files/users/christoffer/bash/config/"
    dest: "/home/christoffer/.config/bash/"
    owner: christoffer
    group: christoffer
    mode: "0644"
    directory_mode: "0755"
    force: true
