---
- name: config | caps2sec | install caps2esc
  ansible.builtin.package:
    name: interception-caps2esc

- name: config | caps2sec | move caps2esc config
  ansible.builtin.copy:
    src: caps2esc/udevmon.yaml
    dest: /etc/udevmon.yaml
    owner: root
    group: root
    mode: "0600"

- name: config | caps2sec | Enable and start udevmon service
  ansible.builtin.systemd_service:
    name: udevmon.service
    enabled: true
    state: started
