ag_package: the_silver_searcher
chromium_package: chromium
cups_package: cups
fira_code_fonts_package: ttf-fira-code
fonts_inconsolata_package: ttf-inconsolata
xfonts_terminus_package: terminus-font
hunspell_en_us_package: hunspell-en_us
hunspell_sv_package: ""
hyphen_en_package: hyphen
hyphen_sv_package: ""
libnotify_package: libnotify
p7zip_package: p7zip
python_dev_package: python-dev
python_setup_tools: python-setuptools
python_pip_pacakge: python-pip
python_virtualenv_package: python-virtualenv
vim_package: gvim
wpasupplicant_package: wpa_supplicant
