ag_package: the_silver_searcher
chromium_package: chromium
cups_package: cups-printerapp
fira_code_fonts_package: fira-code-fonts
fonts_inconsolata_package: levien-inconsolata-fonts
xfonts_terminus_package: terminus-fonts
hunspell_en_us_package: hunspell-en-US
hunspell_sv_package: hunspell-sv
hyphen_en_package: hyphen-en
libnotify_package: libnotify
p7zip_package: p7zip
python_dev_package: python3-devel
python_pip_pacakge: python3-pip
python_setup_tools: python3-setuptools
python_virtualenv_package: python3-virtualenv
samba_client_package: samba-client
vim_package: vim-X11
wpasupplicant_package: wpa_supplicant
