ag_package: silversearcher-ag
chromium_package: chromium
cups_package: cups-daemon
fira_code_fonts_package: fonts-firacode
fonts_inconsolata_package: fonts-inconsolata
xfonts_terminus_package: xfonts-terminus
hunspell_en_us_package: hunspell-en-us
hunspell_sv_package: hunspell-sv
hyphen_en_package: hyphen-en-us
hyphen_sv_package: hyphen-sv
libnotify_package: libnotify-bin
p7zip_package: p7zip-full
python_dev_package: python3-dev
python_pip_pacakge: python3-pip
python_setup_tools: python3-setuptools
python_virtualenv_package: python3-virtualenv
samba_client_package: smbclient
vim_package: vim-gtk3
wpasupplicant_package: wpasupplicant
