---
visual_studio_code_extensions:
  - ms-python.python
  - ms-vscode.cpptools-extension-pack
  - ms-vscode-remote.remote-ssh
  - xaver.clang-format
  - redhat.ansible
  - marlinfirmware.auto-build
  - BeardedBear.beardedtheme
  - donjayamanne.git-extension-pack
  - mhutchie.git-graph
