---
- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    name:
      - ca-certificates
      - colordiff
      - curl
      - dnsutils
      - gcc
      - git
      - htop
      - iotop
      - make
      - nano
      - ncdu
      - net-tools
      - "{{ nfs_package }}"
      - ripgrep
      - rsync
      - tmux
      - traceroute
      - wget
      - whois
    update_cache: true
