---
- name: system setup | tweaks | add flatpak support
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present

- name: system setup | tweaks | add flathub remote
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present
