---
- name: system_setup | fonts | Ensure .fonts exist
  ansible.builtin.file:
    path: "/home/christoffer/.fonts"
    state: directory
    owner: christoffer
    group: christoffer
    mode: '0755'

- name: system_setup | fonts | Install fontconfig
  ansible.builtin.package:
    name:
      - fontconfig
      - unzip

- name: system_setup | fonts | Download and unarchive nerdfonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/3270.zip
    dest: "/home/christoffer/.fonts"
    owner: christoffer
    group: christoffer
    remote_src: true
  retries: 3
  delay: 3
  register: result
  until: result is succeeded

- name: system_setup | fonts | Update font cache
  ansible.builtin.command:
    cmd: fc-cache -fv /home/christoffer/.fonts
  register: output
  changed_when: output.rc != 0
