---
- name: software | utilities | install utility packages
  ansible.builtin.package:
    name:
      - "{{ ag_package }}"
      - bat
      - btop
      - ca-certificates
      - cifs-utils
      - curl
      - direnv
      - gnupg
      - dnsutils
      - fzf
      - htop
      - "{{ hunspell_en_us_package }}"
      - "{{ hunspell_sv_package }}"
      - "{{ hyphen_en_package }}"
      - "{{ hyphen_sv_package }}"
      - iotop
      - jq
      - lsb-release
      - lsof
      - mc
      - nano
      - neovim
      - ncdu
      - net-tools
      - nmap
      - "{{ p7zip_package }}"
      - ripgrep
      - rsync
      - "{{ samba_client_package }}"
      - screen
      - sshpass
      - tmux
      - traceroute
      - unrar
      - vifm
      - "{{ 'vim' if ((ansible_facts['is_wsl'] | default(false)) and ansible_facts['distribution'] == 'Archlinux') else vim_package }}"
      - wget
      - whois
    update_cache: true
  retries: 5
  delay: 15
  register: pkg_install_result
  until: pkg_install_result is succeeded

- name: software | utilities | install desktop packages
  ansible.builtin.package:
    name:
      - arandr
      - "{{ chromium_package }}"
      - "{{ cups_package }}"
      - dconf-editor
      - filezilla
      - "{{ fira_code_fonts_package }}"
      - firefox
      - "{{ fonts_inconsolata_package }}"
      - gparted
      - "{{ libnotify_package }}"
      - libreoffice
      - pavucontrol
      - shutter
      - terminator
      - transmission-gtk
      - vlc
      - "{{ wpasupplicant_package }}"
      - "{{ xfonts_terminus_package }}"
  when: not (ansible_facts['is_wsl'] | default(false))
  retries: 5
  delay: 15
  register: pkg_install_desktop_result
  until: pkg_install_desktop_result is succeeded

- name: software | utilities | install parcelite
  ansible.builtin.package:
    name: parcellite
  when:
    - ansible_facts['distribution'] in ['Ubuntu', 'Debian', 'LMDE']
    - not (ansible_facts['is_wsl'] | default(false))

- name: software | utilities | Download and install broot
  ansible.builtin.get_url:
    url: https://dystroy.org/broot/download/x86_64-linux/broot
    dest: /usr/local/bin/broot
    mode: '777'
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  when: ansible_facts['distribution'] != 'Archlinux'

- name: software | misc |  remove crap workstation packages on debian and ubuntu hosts
  ansible.builtin.package:
    state: absent
    name: [thunderbird*, rhythmbox*, celluoid, hypnotix, hexchat, brltty]
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu", "LMDE"]
