---
- name: server | node-docker | Create service directories
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_id'] }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - homepage
    - speedtest
    - signal-cli
    - alertmanager-signal
    - nginx-proxy-manager
    - promtail
    - WatchYourLAN
    - homelable
    - gatus

- name: server | node-docker | Move promtail-config.yml
  ansible.builtin.template:
    src: common/promtail-config.yml.j2
    dest: "/{{ ansible_facts['user_id'] }}/promtail/promtail-config.yml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: server | node-docker | move docker-compose.yml file to host
  ansible.builtin.template:
    src: "docker/docker-compose.yml.j2"
    dest: "/{{ ansible_facts['user_id'] }}/docker-compose.yml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: server | node-docker | Move alertmanager-signal/config.yaml
  ansible.builtin.template:
    src: "docker/alertmanager-signal/config.yaml.j2"
    dest: "/{{ ansible_facts['user_id'] }}/alertmanager-signal/config.yaml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: server | node-docker | Move homepage config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/{{ ansible_facts['user_id'] }}/homepage/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  loop: "{{ lookup('ansible.builtin.fileglob', role_path ~ '/templates/docker/homepage/*.j2', wantlist=True) }}"

- name: server | node-docker | Move homelable .env file
  ansible.builtin.template:
    src: "docker/homelable/.env.j2"
    dest: "/{{ ansible_facts['user_id'] }}/homelable/.env"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: server | node-docker | Move gatus/config.yaml
  ansible.builtin.template:
    src: "docker/gatus/config.yaml.j2"
    dest: "/{{ ansible_facts['user_id'] }}/gatus/config.yaml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: server | node-docker | deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "/{{ ansible_facts['user_id'] }}/"
    remove_orphans: true
    files:
      - docker-compose.yml
    recreate: always
